In [1]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movie_name = input(' Enter your favourite movie name : ')
movies = pd.read_csv('movies_y.csv')

 Enter your favourite movie name : Heat


In [3]:
movies

index                    genres      id original_language  \
0         0   Animation Comedy Family     862                en   
1         1  Adventure Fantasy Family    8844                en   
2         2            Romance Comedy   15602                en   
3         3      Comedy Drama Romance   31357                en   
4         4                    Comedy   11862                en   
...     ...                       ...     ...               ...   
5269   5269                     Drama  112991                en   
5270   5270             Drama Romance   15677                en   
5271   5271                   Western   58455                en   
5272   5272    Action Adventure Drama   36554                en   
5273   5273              Drama Comedy   48216                fr   

                            title  
0                       Toy Story  
1                         Jumanji  
2                Grumpier Old Men  
3               Waiting to Exhale  
4     Father of the Bride Part II  
...                           ...  
5269          The Sleepy Time Gal  
5270        84 Charing Cross Road  
5271                       Dakota  
5272              The Desert Rats  
5273             Seasons Beatings  

[5274 rows x 5 columns]

In [4]:
#accounting for potential spelling mistakes made by user
list_of_all_titles = movies['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]
print(close_match)

Heat


In [5]:
movies=movies[['index','genres','id','original_language','title']]

In [6]:
#filtering data based on genres and language
selected_features = ['genres','original_language']
print(selected_features)
for feature in selected_features:
  movies[feature] = movies[feature].fillna('')
combined_features = movies['genres']+' '+movies['original_language']

['genres', 'original_language']


In [7]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
similarity = cosine_similarity(feature_vectors)

In [10]:
index_of_the_movie = movies[movies.title == close_match]['index'].values[0]
#calculating similarity scores of all movies with the given movie
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score[1:100])


[(1, 0.03971664406686954), (2, 0.07056053684643478), (3, 0.20174312533363892), (4, 0.10460717919112239), (5, 1.0), (6, 0.07056053684643478), (7, 0.37981695846251), (8, 0.5828016490910221), (9, 0.5828016490910221), (10, 0.20174312533363892), (11, 0.059961850571813406), (12, 0.03595942387041873), (13, 0.156077652628876), (14, 0.3861944306929664), (15, 0.6978447823309664), (16, 0.2377301122470376), (17, 0.5304327915034476), (18, 0.40966417977446606), (19, 0.7350271192095644), (20, 0.7138695566771549), (21, 0.6214421473188616), (22, 0.8017528808913268), (23, 0.2944459637465579), (24, 0.2377301122470376), (25, 0.381512937556368), (26, 0.17111436819590853), (27, 0.2377301122470376), (28, 0.0), (29, 0.3205440940594311), (30, 0.6978447823309664), (31, 0.22533424566272997), (32, 0.0), (33, 0.13215966587543806), (34, 0.13884290227686905), (35, 0.381512937556368), (36, 0.11288583496077008), (37, 0.04955378645898679), (38, 0.20174312533363892), (39, 0.381512937556368), (40, 0.15624890974569766), (

In [11]:
#sorting the list in descending order of similarity scores to extract similar movies
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies[1:100])

[(167, 1.0), (241, 1.0), (255, 1.0), (280, 1.0), (426, 1.0), (477, 1.0), (516, 1.0), (715, 1.0), (967, 1.0), (1569, 1.0), (1677, 1.0), (1725, 1.0), (1726, 1.0), (2221, 1.0), (2366, 1.0), (2377, 1.0), (2611, 1.0), (2641, 1.0), (2654, 1.0), (2697, 1.0), (3138, 1.0), (3246, 1.0), (3307, 1.0), (3310, 1.0), (3312, 1.0), (3314, 1.0), (3639, 1.0), (3772, 1.0), (3821, 1.0), (3876, 1.0), (3913, 1.0), (3957, 1.0), (4074, 1.0), (4135, 1.0), (4234, 1.0), (4479, 1.0), (4646, 1.0), (4759, 1.0), (4777, 1.0), (4804, 1.0), (4817, 1.0), (5047, 1.0), (5065, 1.0), (160, 0.9487974249670676), (474, 0.9487974249670676), (1374, 0.9487974249670676), (1482, 0.9487974249670676), (1556, 0.9487974249670676), (1694, 0.9487974249670676), (1844, 0.9487974249670676), (2626, 0.9487974249670676), (2912, 0.9487974249670676), (3157, 0.9487974249670676), (3217, 0.9487974249670676), (3311, 0.9487974249670676), (3332, 0.9487974249670676), (3560, 0.9487974249670676), (3595, 0.9487974249670676), (3641, 0.9487974249670676), (37

In [12]:
filtered_list = [item for item in sorted_similar_movies if item[1] >= 0.1]
final=np.array(filtered_list)
final=np.delete(final,1,1)
arr= final.astype(int)
values_array = movies['id'].values[arr]
# title_array=movies['title'].values[arr]
print(values_array)

[[  949]
 [10428]
 [72031]
 ...
 [10326]
 [35936]
 [18937]]


In [13]:
ratings = pd.read_csv('Ratings_mov.csv')
ratings.rename(columns={'movieId':'id'},inplace=True)
print(ratings)

        userId    id  rating   timestamp
0            1    31     2.5  1260759144
1            1  1029     3.0  1260759179
2            1  1061     3.0  1260759182
3            1  1129     2.0  1260759185
4            1  1172     4.0  1260759205
...        ...   ...     ...         ...
99999      671  6268     2.5  1065579370
100000     671  6269     4.0  1065149201
100001     671  6365     4.0  1070940363
100002     671  6385     2.5  1070979663
100003     671  6565     3.5  1074784724

[100004 rows x 4 columns]


In [14]:
#taking movies that are filtered
filtered_values = ratings.loc[np.isin(ratings['id'], values_array), 'id']
ratings = ratings[ratings.index.isin(filtered_values.index)]
ratings_with_name = movies.merge(ratings,on='id')
ratings_with_name=ratings_with_name[['index','id','title','rating','userId']]

#finding intelligent users and good movies
x = ratings_with_name.groupby('userId').count()['rating'] > 50
intelligent_users = x[x].index
filtered_rating = ratings_with_name[ratings_with_name['userId'].isin(intelligent_users)]
y = filtered_rating.groupby('title').count()['rating']>=10
famous_movies = y[y].index
ratings_with_name = filtered_rating[filtered_rating['title'].isin(famous_movies)]

print(ratings_with_name)

       index    id   title  rating  userId
0          5   949    Heat     3.5      23
1          5   949    Heat     4.0     102
2          5   949    Heat     2.0     232
3          5   949    Heat     5.0     242
5          5   949    Heat     3.0     311
...      ...   ...     ...     ...     ...
15076   5253  1957  Enough     1.0     564
15077   5253  1957  Enough     5.0     575
15078   5253  1957  Enough     5.0     577
15080   5253  1957  Enough     4.0     605
15081   5253  1957  Enough     3.0     608

[4795 rows x 5 columns]


In [15]:
#matrix factorization
pt = ratings_with_name.pivot_table(index='title',columns='userId',values='rating')
pt.fillna(0,inplace=True)
print(pt)

userId                        15   17   19   23   30   73   86   88   102  \
title                                                                       
20,000 Leagues Under the Sea  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0   
48 Hrs.                       3.0  0.0  3.0  3.5  5.0  3.5  4.0  4.0  4.0   
A Clockwork Orange            2.0  3.0  0.0  3.5  0.0  2.5  0.0  3.0  0.0   
A Perfect Murder              0.0  0.0  0.0  0.0  4.0  3.5  0.0  0.0  4.0   
A River Runs Through It       5.0  4.0  4.0  4.0  0.0  5.0  0.0  0.0  0.0   
...                           ...  ...  ...  ...  ...  ...  ...  ...  ...   
Wag the Dog                   2.0  0.0  3.0  3.5  4.0  3.5  1.0  2.5  0.0   
Whats Eating Gilbert Grape    0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0   
While You Were Sleeping       4.5  0.0  0.0  0.0  4.0  0.0  0.0  0.0  4.0   
Young and Innocent            1.0  4.5  0.0  4.0  5.0  4.0  0.0  4.0  4.0   
eXistenZ                      0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  4.0   

In [16]:
ratings_with_name.drop_duplicates(['userId','title'],inplace=True)
# print(ratings_with_name)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pt)
print(similarity_scores)

[[1.         0.41405977 0.46404789 ... 0.12574756 0.45538864 0.        ]
 [0.41405977 1.         0.55063446 ... 0.47247902 0.70239909 0.36768713]
 [0.46404789 0.55063446 1.         ... 0.12489763 0.57735827 0.0678586 ]
 ...
 [0.12574756 0.47247902 0.12489763 ... 1.         0.53918366 0.48932338]
 [0.45538864 0.70239909 0.57735827 ... 0.53918366 1.         0.3844915 ]
 [0.         0.36768713 0.0678586  ... 0.48932338 0.3844915  1.        ]]


In [18]:
indices=np.where(pt.index==close_match)

In [19]:
print("Movies you may like\n")
j = 1
for movie in sorted_similar_movies:
    idx = movie[0]

    title_from_index = movies[movies.index==idx]['title'].values[0]
    if (j<10):
        
        if(j==1):
            j+=1
            continue 
        print(j-1, '.',title_from_index)
        j+=1  

if len(indices[0]) != 0:
    index = indices[0][0]
    similarity_score_n = list(enumerate(similarity_scores[index]))
    similar_movies = sorted(similarity_score_n, key = lambda x:x[1], reverse = True) 
    
    
    i = 1
    print("\nPeople also liked\n")
    for movie in similar_movies:
        idx = movie[0]
        #   title_from_index = ratings_with_name[ratings_with_name.index==idx]['title'].values[0]
        title_from_index = ratings_with_name[ratings_with_name['title'] == pt.index[idx]].values[0][2]
        if (i<10):
            if(i==1):
                i+=1
                continue
            print(i-1, '.',title_from_index)
            i+=1

Movies you may like

1 . Hackers
2 . The Glass Shield
3 . Kiss of Death
4 . New York Cop
5 . Carlitos Way
6 . Killing Zoe
7 . Romeo Is Bleeding
8 . Original Gangstas

People also liked

1 . Nell
2 . Escape from New York
3 . The Bachelor
4 . eXistenZ
5 . Alien
6 . The Big Sleep
7 . Enough
8 . Star Wars
